In [202]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
import time
import psutil
import numpy as np
from sklearn import datasets

file_path = 'D:\Programming\Datasets\healthcare-dataset-stroke-data.csv'
    
df = pd.read_csv(file_path)

In [203]:
def replace_with_noise(dataframe, percentage=0.1):
    # Setting the seed to ensure reproducibility
    np.random.seed(0)

    # Generate the random indices to be replaced
    num_rows = len(dataframe)
    num_replace = int(num_rows * percentage)
    idx = np.random.choice(np.arange(num_rows), size=num_replace, replace=False)

    # Generate noise equivalent to the number of replacements
    noise = np.random.normal(0, 1, num_replace)

    # Make a copy of the dataframe
    df_noisy = dataframe.copy()

    # Replace the selected indices with noise
    last_col = df_noisy.columns[-1]
    
    for column in df_noisy.columns[:-1]:
        df_noisy.loc[idx, column] = noise
        
    df_noisy.loc[idx, last_col] = df_noisy.loc[idx, last_col]

    return df_noisy

In [204]:
df_noisy1 = replace_with_noise(df, 0.9)
df_noisy1

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046.000000,Male,67.000000,0.000000,1.000000,Yes,Private,Urban,228.690000,36.600000,formerly smoked,1
1,0.278643,0.278643,0.278643,0.278643,0.278643,0.278643,0.278643,0.278643,0.278643,0.278643,0.278643,1
2,0.215187,0.215187,0.215187,0.215187,0.215187,0.215187,0.215187,0.215187,0.215187,0.215187,0.215187,1
3,1.219841,1.219841,1.219841,1.219841,1.219841,1.219841,1.219841,1.219841,1.219841,1.219841,1.219841,1
4,-0.728109,-0.728109,-0.728109,-0.728109,-0.728109,-0.728109,-0.728109,-0.728109,-0.728109,-0.728109,-0.728109,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,1.246255,1.246255,1.246255,1.246255,1.246255,1.246255,1.246255,1.246255,1.246255,1.246255,1.246255,0
5106,0.231217,0.231217,0.231217,0.231217,0.231217,0.231217,0.231217,0.231217,0.231217,0.231217,0.231217,0
5107,0.902003,0.902003,0.902003,0.902003,0.902003,0.902003,0.902003,0.902003,0.902003,0.902003,0.902003,0
5108,0.479722,0.479722,0.479722,0.479722,0.479722,0.479722,0.479722,0.479722,0.479722,0.479722,0.479722,0
5109,-0.292001,-0.292001,-0.292001,-0.292001,-0.292001,-0.292001,-0.292001,-0.292001,-0.292001,-0.292001,-0.292001,0

In [205]:
features = ['age', 'hypertension', 'heart_disease', 'avg_glucose_level']
target = 'stroke'

X = df_noisy[features]
y = df_noisy[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [206]:
svm_classifier = SVC(kernel='linear')

start_training_time = time.time()

svm_classifier.fit(X_train, y_train)

end_training_time = time.time()
training_time_duration = end_training_time - start_training_time

In [207]:
start_testing_time = time.perf_counter()

# Predict on the test set
y_pred = svm_classifier.predict(X_test)

end_testing_time = time.perf_counter()
testing_time_duration = end_testing_time - start_testing_time

In [208]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

print(f"Training Time: {training_time_duration:.8f} seconds")
print(f"Testing Time: {testing_time_duration:.8f} seconds")

Confusion Matrix:
[[1444    0]
 [  89    0]]
Accuracy: 94.19%
Training Time: 112.95219803 seconds
Testing Time: 0.01436830 seconds